language: bash

sudo: required

notifications:
  email: false

before_install:
  - sudo apt-get install $(grep -vE "^\s*#" apt-build-requirements.txt | tr "\n" " ")

script:
  - bash scripts/setup_virtualenv.sh $(pwd) true