#!/bin/bash

if cd /usr/local/src/mkat_fpga > /dev/null 2&>1; then
        echo 'Updating mkat_fpga' [$(git symbolic-ref --short HEAD)]
        git pull
else
        echo 'Failed to update mkat_fpga'
fi

printf '*****************************************************************\n'

if cd /usr/local/src/casperfpga > /dev/null 2&>1; then
        echo 'Updating casperfpga' [$(git symbolic-ref --short HEAD)]
	if git pull > /dev/null 2&>1; then
                printf '\033[32mSuccessfully pulled latest changes\n\n\033[0m'
        else
                printf '\e[31mFailed to pull latest changes, reasons unknown\n\n\e[0m\n'
        fi
	sudo python setup.py install -f
else
        echo 'Failed to update casperfpga'
fi
printf '*****************************************************************\n'
if cd /usr/local/src/corr2 > /dev/null 2&>1; then
        echo 'Updating corr2' [$(git symbolic-ref --short HEAD)]
        if git pull > /dev/null 2&>1; then
                printf '\033[32mSuccessfully pulled latest changes\n\n\033[0m'
        else
                printf '\e[31mFailed to pull latest changes, reasons unknown\n\n\e[0m\n'
        fi
        sudo python setup.py install -f
else
        echo 'Failed to update corr2'
fi
printf '\033[32mDone\033[0m'
