#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:$PATH

set -e

if [ $# -lt 1 ] ; then
  echo "need a roach pretending to be a digitiser, possible options: "
  ike -s dsimengine -k host -o  /etc/corr/* | sort -u
  exit 1
fi

kcs -d -p 9010 -l /dev/null
sleep 1 
export KATCP_SERVER=localhost:9010
kcpcmd -i listener-create default 9011
export KATCP_SERVER=localhost:9011
kcpcmd -i client-exec pseudo-dmc-child default pseudo-dmc-child $1

echo "running a pretend dmc on ${KATCP_SERVER}"
