#!/bin/bash
PORT=$(kcpcmd array-list | grep array-list | cut -f3 -d' ' | cut -f1 -d',')
SENSORPORT=$(kcpcmd array-list | grep array-list | cut -f3 -d' ' | cut -f2 -d',')

#kcpcmd -s localhost:$PORT sensor-value | grep map
#echo Hello World

export TESTVAR=$(kcpcmd -s localhost:$PORT sensor-value | grep weight)

#echo TESTVAR = $TESTVAR
echo $TESTVAR



